### PR TITLE
2.Homework

### PR DESCRIPTION
**Pull request by karlijaanson**

### CODE REVIEW

**Comment by romilrobtsenkov** [comment]
@karlijaanson both files are broken
```
Parse error: syntax error, unexpected '}' in /home/romil/public_html/web/2hw/karlijaanson/app.php on line 55

Unknown column 'milestone' in 'field list' Fatal error: Call to a member function bind_result() on a non-object in /home/romil/public_html/web/2hw/karlijaanson/table.php on line 49
```

**Comment by karlijaanson** [comment]
@romilrobtsenkov Is something wrong with the coding or the file is interrupted? I can't find the reason what caused the problem.

**Comment by karlijaanson** [comment]
@romilrobtsenkov Files fixed.

**Comment by karlijaanson** [comment]
@romilrobtsenkov Fixed both files!

**Comment by romilrobtsenkov** [comment]
@karlijaanson nice!

**Pull request closed without merging**
